name: "PR description check"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: nouzbe/check-pull-request-description@v1.11
      - uses: superbrothers/close-pull-request@v3
          with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "We do not accept PR for main , due to closeing this PR."
